all: ABAG2005_orig.gdb.zip input_watersheds.gdb.zip

ABAG2005_orig.gdb.zip:
	wget https://maps.californiawetlands.net/rwsm_files/ABAG2005_orig.gdb.zip

input_watersheds.gdb.zip:
	wget https://maps.californiawetlands.net/rwsm_files/input_watersheds.gdb.zip
